# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  KoscianyPoker_config = debug

else ifeq ($(config),release)
  KoscianyPoker_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := KoscianyPoker

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

KoscianyPoker:
ifneq (,$(KoscianyPoker_config))
	@echo "==== Building KoscianyPoker ($(KoscianyPoker_config)) ===="
	@${MAKE} --no-print-directory -C . -f KoscianyPoker.make config=$(KoscianyPoker_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f KoscianyPoker.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   KoscianyPoker"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"